// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtu2Q6Gv9oENh4DaL9pTb2O6asVrJWs4M',
    appId: '1:239296983702:web:4b2f4dc89dba2bd94288b7',
    messagingSenderId: '239296983702',
    projectId: 'ecommerceapp-a4bd9',
    authDomain: 'ecommerceapp-a4bd9.firebaseapp.com',
    storageBucket: 'ecommerceapp-a4bd9.appspot.com',
    measurementId: 'G-31C0XG8611',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcS-0iNv53-mbIwBEYLeLSjaRKdYwE3BU',
    appId: '1:239296983702:android:963b5bbd8f69b0ab4288b7',
    messagingSenderId: '239296983702',
    projectId: 'ecommerceapp-a4bd9',
    storageBucket: 'ecommerceapp-a4bd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvtcRrXdepN64_YAyPn730pcygPdsmPmM',
    appId: '1:239296983702:ios:0133e3a35ac40af64288b7',
    messagingSenderId: '239296983702',
    projectId: 'ecommerceapp-a4bd9',
    storageBucket: 'ecommerceapp-a4bd9.appspot.com',
    iosClientId: '239296983702-6o8qvd7sngohvdf0h9nsumk88bctaqe0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvtcRrXdepN64_YAyPn730pcygPdsmPmM',
    appId: '1:239296983702:ios:bcd6cf01de3a38254288b7',
    messagingSenderId: '239296983702',
    projectId: 'ecommerceapp-a4bd9',
    storageBucket: 'ecommerceapp-a4bd9.appspot.com',
    iosClientId: '239296983702-k5bborbru7km971hvlkuuvep1n01dcn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
